#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Load Laravel
|--------------------------------------------------------------------------
|
| We load the laravel runtime so that we can illuminate stuff.
|
*/
require __DIR__.'/bootstrap/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';


/*
|--------------------------------------------------------------------------
| Register the kernel
|--------------------------------------------------------------------------
|
| Laravel registers all of it's kernels in the bootstrap/app; we'll register ours here.
| That way it's only ever even loaded when you perform a socket request.
|
*/
$app->singleton(\Experus\Sockets\Contracts\Kernel::class,
    \Experus\Sockets\Core\SocketKernel::class
);

$kernel = $app->make(\Experus\Sockets\Contracts\Kernel::class);

$kernel->init(
    new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->listen();